- hosts: all
  tasks:
    - name: install httpd package
      package:
         name: "httpd"
         state: present
      when: ansible_distribution == "RedHat"
      register: x

    - name: document root directory
      file:
        state: directory
        dest: "/var/www/prakhar"
      register: dcdir_status

      # - debug:
      #  var: dcdir_status

    - name: configure webserver
      copy: 
        src: localconf.conf
        dest: /etc/httpd/conf.d/prakhar.conf
      when: x.rc == 0
      notify: service httpd  

    - name: copy web page from URL
      get_url:
          dest: "/var/www/prakhar"
          url: "https://raw.githubusercontent.com/prakhar1508/devopsal2/master/web.html"
      when: dcdir_status.failed == false
      tags: webgit

  handlers:
    - name: service httpd
      service:
          name: "httpd"
          state: restarted
